## handling null value

#########################################################################################################################

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 

df =pd.read_csv(r'C:\Users\Dhruv stark\Desktop\machine learning practice\NameAgeSalary.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0         Name   Age  Salary  4 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes

In [8]:
df=pd.read_csv(r'C:\Users\Dhruv stark\Desktop\machine learning practice\NameAgeSalary.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0         Name   Age  Salary  4 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes

## NaN (Not a Number)
1) None
2) Empty strings (“”)
3) Markers like “?”, “N/A”

## Techniques to Handle Null Values
So, how do we handle missing data? We’ve got a few options, and the best one depends on the type of missing data and the size of the gaps in our dataset.

1. ## Removing Null Values
We can simply remove the rows or columns with null values. This works when there are only a few missing entries and we don’t mind losing a bit of data.

In [22]:
df=pd.read_csv(r'C:\Users\Dhruv stark\Desktop\machine learning practice\market_data.csv')
df.head(20)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350
10,FDY07,11.800,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530
12,FDX32,15.100,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1,2145.2076
14,FDF32,16.350,Low Fat,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,High,Tier 3,Supermarket Type1,1977.4260
15,FDP49,9.000,Regular,0.069089,Breakfast,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192
16,NCB42,11.800,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
17,FDP49,9.000,Regular,0.069196,Breakfast,54.3614,OUT049,1999,Medium,Tier 1,Supermarket Type1,718.3982
18,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
19,FDU02,13.350,Low Fat,0.102492,Dairy,230.5352,OUT035,2004,Small,Tier 2,Supermarket Type1,2748.4224

In [20]:
df.shape

(8523, 12)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [24]:
df.dropna(inplace=True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4650 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            4650 non-null   object
 1   Item_Weight                4650 non-null   float64
 2   Item_Fat_Content           4650 non-null   object
 3   Item_Visibility            4650 non-null   float64
 4   Item_Type                  4650 non-null   object
 5   Item_MRP                   4650 non-null   float64
 6   Outlet_Identifier          4650 non-null   object
 7   Outlet_Establishment_Year  4650 non-null   int64
 8   Outlet_Size                4650 non-null   object
 9   Outlet_Location_Type       4650 non-null   object
 10  Outlet_Type                4650 non-null   object
 11  Item_Outlet_Sales          4650 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 472.3+ KB

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4650 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            4650 non-null   object
 1   Item_Weight                4650 non-null   float64
 2   Item_Fat_Content           4650 non-null   object
 3   Item_Visibility            4650 non-null   float64
 4   Item_Type                  4650 non-null   object
 5   Item_MRP                   4650 non-null   float64
 6   Outlet_Identifier          4650 non-null   object
 7   Outlet_Establishment_Year  4650 non-null   int64
 8   Outlet_Size                4650 non-null   object
 9   Outlet_Location_Type       4650 non-null   object
 10  Outlet_Type                4650 non-null   object
 11  Item_Outlet_Sales          4650 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 472.3+ KB

## Why this is a problem for ML
Dropping 45% of your data is almost always wrong for a real project. Better approaches:

###########################################################################################################################

## Imputation
Imputation is about filling in the missing values with estimates, making our dataset complete again. There are several ways to do this:

Mean/Median/Mode Imputation: Fill in the missing value with the average, median, or most common value in the column.

In [29]:
df=pd.read_csv(r'C:\Users\Dhruv stark\Desktop\machine learning practice\market_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [34]:
#impute the null value with numerical value 

df['Item_Weight'].fillna(df['Item_Weight'].median(),inplace=True)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [42]:
#impute the null value with the mode to the object non numerical value 
df['Outlet_Size'].fillna(df['Outlet_Size'].mode()[0],inplace=True)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                8523 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

## K-Nearest Neighbors (KNN) Imputation: Use similar data points (neighbors) to predict the missing value.

In [46]:
df=pd.read_csv(r'C:\Users\Dhruv stark\Desktop\machine learning practice\market_data.csv')
df.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [1]:
from sklearn.impute import KNNImputer 

## KNNImputer only works on numeric columns
# So separate numeric and categorical first

nurmeric_col =['Item_Weight','Item_Visibility', 'Item_MRP', 'Outlet_Establishment_Year', 'Item_Outlet_Sales']
imputer = KNNImputer(n_neighbors=5)
df[nurmeric_col] = imputer.fit_transform(df[nurmeric_col])

#caterigorial columns uses the mode method 
df.info()

AttributeError: 'KNNImputer' object has no attribute 'fit_tr'

In [50]:
df.head(20)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999.0,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009.0,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999.0,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998.0,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987.0,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009.0,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987.0,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,16.850,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985.0,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002.0,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007.0,NaN,Tier 2,Supermarket Type1,4710.5350
10,FDY07,11.800,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999.0,Medium,Tier 1,Supermarket Type1,1516.0266
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997.0,Small,Tier 1,Supermarket Type1,2187.1530
12,FDX32,15.100,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999.0,Medium,Tier 1,Supermarket Type1,1589.2646
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997.0,Small,Tier 1,Supermarket Type1,2145.2076
14,FDF32,16.350,Low Fat,0.068024,Fruits and Vegetables,196.4426,OUT013,1987.0,High,Tier 3,Supermarket Type1,1977.4260
15,FDP49,9.000,Regular,0.069089,Breakfast,56.3614,OUT046,1997.0,Small,Tier 1,Supermarket Type1,1547.3192
16,NCB42,11.800,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009.0,Medium,Tier 3,Supermarket Type2,1621.8888
17,FDP49,9.000,Regular,0.069196,Breakfast,54.3614,OUT049,1999.0,Medium,Tier 1,Supermarket Type1,718.3982
18,DRI11,13.755,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985.0,Medium,Tier 3,Supermarket Type3,2303.6680
19,FDU02,13.350,Low Fat,0.102492,Dairy,230.5352,OUT035,2004.0,Small,Tier 2,Supermarket Type1,2748.4224


#########################################################################################################

## this not profgessionL WAY TO HANDLE THE NULL OR MISSING VALUE 
BECAUSE WHEN WE USE MODE OR MEAN ON TRAIN DATASET THAT MEANS THE FUTURE DATA DOESNT CONTAIN THE 
MEDIAN BECAUSE ITS UNPREDICTABLE 
ONLY USE THIS FOR INSPECTION !!!!!!!!
##########################################################################################################

Three types of missing data:
TypeMeaningExample
MCAR — Missing Completely At RandomNo pattern, just randomsensor glitch
MAR — Missing At Random Null depends on other columns heavier items have weight recorded more
MNAR — Missing Not At Random Null itself is informative rich people skip income field